### ISSUE TITLE
Unable to run jar compendium-of-test-apps-1-3-7.jar

### ISSUE THREAD

**Issue by nikhilpereira1793** [eviltester/TestingApp#2]
Hi, Thank you for creating this application. I am facing an issue when I am trying to run it.

After cloning and building the app in `java-testing/TestingApp/java` directory using `mvn package`, I went to `/testingapps/testingapp/target/` folder and ran `java -jar compendium-of-test-apps-1-3-7.jar` and I got error - no main manifest attribute, in compendium-of-test-apps-1-3-7.jar. When I checked the manifest file after unzipping it is not having the main class attribute.

```
Manifest-Version: 1.0
Archiver-Version: Plexus Archiver
Built-By: nikhil_pereira
Created-By: Apache Maven 3.6.1
Build-Jdk: 1.8.0_152
```

**Comment by eviltester** [comment]
Hi,

I normally recommend using the pre-built jars from the release page.

Bult when built from code you should see at least two .jar files

- `compendium-of-test-apps-1-3-7.jar` is the library version
- `compendium-of-test-apps-1-3-7-jar-with-dependencies.jar` is the runnable version with the manifest and all dependencies packaged together

`java -jar compendium-of-test-apps-1-3-7-jar-with-dependencies.jar`

should hopefully work

If you want to run any of the applications individually then they should be in target subfolders for each application. Again use the `X-with-dependencies.jar`

**Comment by nikhilpereira1793** [comment]
thank you :)
